### ISSUE TITLE
VPC Config Support

### ISSUE THREAD

**Issue by mcblair** [wata727/drunker#11]
Does drunker have the ability to specify subnets or VPC id?

**Comment by wata727** [comment]
Now, drunker can't specify it. However, I'd like to add this feature.
If you have a patch, please send it. I'll review your pull request :)

**Comment by mcblair** [comment]
Unfortunately I don't have any Ruby experience. I took some time to understand drunker's consumption of the Ruby SDK for AWS and I think I could get it to work - I don't think I can write acceptable tests for the additional parameters.

I'm working directly with AWS Codebuild now(more work than drunker) because I needed VPC access yesterday.

I may submit a PR if I have time and you feel like guiding me on the tests.
